# Generated by Django 3.0.6 on 2020-06-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200609_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(default='', upload_to='', verbose_name='choose your photo'),
        ),
    ]
