# Generated by Django 3.0.6 on 2020-06-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default='', upload_to='', verbose_name='choose your photo'),
        ),
    ]
